### ISSUE TITLE
FileNotFoundError ,How i get it *.nii.gz?

### ISSUE THREAD

**Issue by masmai** [sergivalverde/cnn-ms-lesion-segmentation#3]
---> cnn1 loading training data
Traceback (most recent call last):
  File "train_leave_one_out.py", line 79, in <module>
    model = train_cascaded_model(model, train_x_data, train_y_data,  options)
  File "C:\Users\MAGARA\Downloads\Compressed\cnn-ms-lesion-segmentation-master\base.py", line 35, in train_cascaded_model
    X, Y = load_training_data(train_x_data, train_y_data, options)
  File "C:\Users\MAGARA\Downloads\Compressed\cnn-ms-lesion-segmentation-master\base.py", line 134, in load_training_data
    x_patches, y_patches = load_train_patches(x_data, y_data, selected_voxels, options['patch_size'])
  File "C:\Users\MAGARA\Downloads\Compressed\cnn-ms-lesion-segmentation-master\base.py", line 205, in load_train_patches
    lesion_masks = [load_nii(name).get_data().astype(dtype=np.bool) for name in y_data]
  File "C:\Users\MAGARA\Anaconda2\lib\site-packages\nibabel\loadsave.py", line 40, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file: 'C:\Users\MAGARA\Downloads\Compressed\cnn-ms-lesion-segmentation-master\VH_all\im3\lesion_bin.nii.gz'

**Comment by mengluffy** [comment]
yes , me too. I don't know how to options folder, my nii.gz file all in one folder.

**Comment by sergivalverde** [comment]
Hi @masmai @mengluffy 

Following [the provided example notebook](https://github.com/sergivalverde/cnn-ms-lesion-segmentation/blob/master/example_1.ipynb), each training image is inside a folder: 

````python
train_folder = '/mnt/DATA/w/CNN/images/train_images'
train_x_data = {}
train_y_data = {}

# TRAIN X DATA
train_x_data['im1'] = {'T1': os.path.join(train_folder,'im1', 'T1.nii.gz'), 
                       'FLAIR': os.path.join(train_folder,'im1', 'T1.nii.gz')}
train_x_data['im2'] = {'T1': os.path.join(train_folder,'im2', 'T1.nii.gz'), 
                       'FLAIR': os.path.join(train_folder,'im2', 'T1.nii.gz')}
train_x_data['im3'] = {'T1': os.path.join(train_folder,'im3', 'T1.nii.gz'), 
                       'FLAIR': os.path.join(train_folder,'im3', 'T1.nii.gz')}

# TRAIN LABELS 
train_y_data['im1'] = os.path.join(train_folder,'im1', 'lesion_bin.nii.gz')
train_y_data['im2'] = os.path.join(train_folder,'im2', 'lesion_bin.nii.gz')
train_y_data['im3'] = os.path.join(train_folder,'im3', 'lesion_bin.nii.gz')
````

So, your input folder should be something like: 

````
[training_folder] 
                        [im1 folder]
                                            flair.nii.gz
                                            t1.nii.gz
                                            lesion_bin.nii.gz
                        [im2 folder]
                                            flair.nii.gz
                                            t1.nii.gz
                                            lesion_bin.nii.gz
                        
                       ...
                       
                        [im_n folder]
                                           flair.nii.gz
                                           t1.nii.gz
                                           lesion_bin.nii.gz
````

where image folders names are used as keys in the dictionary `train_x_data`

Take into account that you can call the training images differently simply filling the dictionary in other ways. For instance, if you have all training mages inside the same folder, then:

````python
train_folder = '/path/to/training/images/'
train_x_data = {}
train_y_data = {}

# TRAIN X DATA
train_x_data['im1_id'] = {'T1': os.path.join(train_folder, 'T1_im1.nii.gz'), 
                       'FLAIR': os.path.join(train_folder, 'FLAIR_im1.nii.gz')}
train_x_data['im2_id'] = {'T1': os.path.join(train_folder, 'T1_im2.nii.gz'), 
                       'FLAIR': os.path.join(train_folder, 'FLAIR_im2.nii.gz')}
train_x_data['im3_id'] = {'T1': os.path.join(train_folder, 'T1_im3.nii.gz'), 
                       'FLAIR': os.path.join(train_folder,  'FLAIR_im3.nii.gz')}

# TRAIN LABELS 
train_y_data['im1_id'] = os.path.join(train_folder, 'lesion_bin_im1.nii.gz')
train_y_data['im2_id'] = os.path.join(train_folder,'lesion_bin_im2.nii.gz')
train_y_data['im3_id'] = os.path.join(train_folder,'lesion_bin_im3.nii.gz')
````
hope it helps,

**Comment by masmai** [comment]
I'm sorry to make you misunderstand. Actually, I've  already put "traning_folder" Follow the instructions.
But I do not know where to find Traning images?

**Comment by sergivalverde** [comment]
I'm sorry but the repository do not provide training images.

**Comment by mengluffy** [comment]
I change folder in my computer, don't in code,  than have another error 
Traceback (most recent call last):
  File "/home/kmust/cnnsg/train_leave_one_out.py", line 79, in <module>
    model = train_cascaded_model(model, train_x_data, train_y_data,  options)
  File "/home/kmust/cnnsg/base.py", line 42, in train_cascaded_model
    X, Y = load_training_data(train_x_data, train_y_data, options)
  File "/home/kmust/cnnsg/base.py", line 140, in load_training_data
    y_data = [train_y_data[s] for s in scans]
KeyError: 'im1'

**Comment by sergivalverde** [comment]
And what's the question?
 
It's obvious that something is wrong with the dictionary, isn't it? The dictionary keys should correspond to the image folder names. Just with this information is very difficult to help: 
Look at this: 

https://github.com/sergivalverde/cnn-ms-lesion-segmentation/blob/master/train_leave_one_out.py#L44

**Comment by sergivalverde** [comment]
Original images are in nrrd format. You have to convert them.  see here
<https://stackoverflow.com/questions/47761353/nrrd-to-nifti-file-conversion?rq=1>for
instance on how to do it.

**Comment by melrobin** [comment]
OK, thanks!  I was able to perform the conversion.
